# Generated by Django 2.0.1 on 2018-04-15 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='department_code',
            new_name='department_ss',
        ),
    ]
