# Generated by Django 2.0.1 on 2018-04-15 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acads', '0002_auto_20180415_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='department_ss',
            field=models.CharField(choices=[('it', 'IT'), ('cse', 'CSE'), ('eee', 'EEE'), ('mech', 'MECH'), ('ece', 'ECE'), ('civil', 'CIV')], default='it', max_length=3),
        ),
    ]
