# Generated by Django 2.0.1 on 2018-04-15 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acads', '0003_auto_20180415_0935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='department_ss',
            new_name='department_code',
        ),
    ]
