# Generated by Django 2.0.1 on 2018-04-15 04:07

import acads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acads', '0004_auto_20180415_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to=acads.models.get_file_path),
        ),
    ]
