# Generated by Django 2.0.1 on 2018-04-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acads', '0005_auto_20180415_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='year',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=1),
        ),
    ]
