# Generated by Django 2.0.1 on 2018-04-15 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acads', '0006_document_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='year',
            new_name='year_code',
        ),
    ]
